# Generated by Django 2.2.5 on 2021-01-02 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210102_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 7, 20, 22, 10128, tzinfo=utc)),
        ),
    ]
