# Generated by Django 2.2.5 on 2021-01-02 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210102_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 11, 38, 4, 951865, tzinfo=utc)),
        ),
    ]
