# Generated by Django 2.2.5 on 2021-01-02 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210102_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 13, 14, 8, 684814, tzinfo=utc)),
        ),
    ]
