# Generated by Django 2.2.5 on 2021-01-02 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210102_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 13, 27, 55, 884857, tzinfo=utc)),
        ),
    ]
